#!/usr/bin/python

Import('env')

source = """
    main.c
    cfg.c
    log.c
    job.c
    model.c
    acl.c
    notify.c
    event.c
    process.c
    csl.c
    data.c
    rpc_unix.c
    utility.c
    iksemel.c
"""

comar = env.Program("comar", Split(source))

Return('comar')
