Import('env')

libcomar = env.SharedLibrary("libcomar", [ "libcomar.c" ])
hav = env.Program("hav", [ "libcomar.c", "hav.c" ])

env.Install(env['prefix'] + '/usr/include', 'libcomar.h')
env.Install(env['prefix'] + '/usr/lib', libcomar)
env.Install(env['prefix'] + '/usr/bin', hav)

env.Alias('install', [env['prefix'] + '/usr/include', env['prefix'] + '/usr/lib', env['prefix'] + '/usr/bin'])
