#!/usr/bin/python

import os

Import('env')
prefix = ARGUMENTS.get('prefix', "")

libcomar = env.SharedLibrary("libcomar", [ "libcomar.c" ])
hav = env.Program("hav", [ "libcomar.c", "hav.c" ])
env.Install(os.path.join(prefix, 'usr/include'), 'libcomar.h')
env.Install(os.path.join(prefix, 'usr/lib'), libcomar)
env.Install(os.path.join(prefix, 'usr/bin'), hav)
